### ISSUE TITLE
Deopt explorer attempts to reference file that does not exist and crashes

### ISSUE THREAD

**Issue by millerick** [microsoft/deoptexplorer-vscode#21]
Running node 18.14.2 and invoking with the following to produce the log file to analyze.
```
node --log-deopt --log-ic --log-maps --log-maps-details --log-code --log-source-code --prof --log-internal-timer-events --detailed-line-info --logfile=/System/Volumes/Data/src/lending/backend/v8.log --no-logfile-per-isolate ./dist/cluster-web.js -p ./
```
After https://github.com/microsoft/deoptexplorer-vscode/issues/11 was addressed, I am once again trying to use the deopt explorer on my company's largest node project.  The extension processes the log file that was created, but then crashes when it cannot find a file on the file system.
```
[INFO: 08:44:45.698] Detected log for V8 10.2.154.26-node.22
[ERR!: 08:45:18.462] dropping: overflow
[INFO: 08:46:45.627] processContent took 121,175.0ms
[INFO: 08:46:50.841] Error: ENOENT: no such file or directory, realpath '/System/Volumes/Data/src/lending/backend/node_modules/uri-js/src/index.ts'
    at Function.realpathSync.native (node:fs:2602:3)
    at Function.native (node:electron/js2c/asar_bundle:2:4804)
    at h (/Users/mmillerick/.vscode/extensions/rbuckton.deoptexplorer-vscode-1.1.0-darwin-arm64/dist/extension.js:5:28829)
    at f (/Users/mmillerick/.vscode/extensions/rbuckton.deoptexplorer-vscode-1.1.0-darwin-arm64/dist/extension.js:5:28959)
    at /Users/mmillerick/.vscode/extensions/rbuckton.deoptexplorer-vscode-1.1.0-darwin-arm64/dist/extension.js:2:110463
    at Array.map (<anonymous>)
    at t.SourceMap.get sources [as sources] (/Users/mmillerick/.vscode/extensions/rbuckton.deoptexplorer-vscode-1.1.0-darwin-arm64/dist/extension.js:2:110434)
    at /Users/mmillerick/.vscode/extensions/rbuckton.deoptexplorer-vscode-1.1.0-darwin-arm64/dist/extension.js:2:175455
    at t.measureAsync (/Users/mmillerick/.vscode/extensions/rbuckton.deoptexplorer-vscode-1.1.0-darwin-arm64/dist/extension.js:5:27435)
    at t.LogProcessor.process (/Users/mmillerick/.vscode/extensions/rbuckton.deoptexplorer-vscode-1.1.0-darwin-arm64/dist/extension.js:2:174925)
    at /Users/mmillerick/.vscode/extensions/rbuckton.deoptexplorer-vscode-1.1.0-darwin-arm64/dist/extension.js:5:41968 {
  errno: -2,
  syscall: 'realpath',
  code: 'ENOENT',
  path: '/System/Volumes/Data/src/lending/backend/node_modules/uri-js/src/index.ts'
}
```
It is correct that the file does not exist on the file system:
```
(lending-dev) (i386)(v18.14.2) /src/lending/backend (master) $ cat /System/Volumes/Data/src/lending/backend/node_modules/uri-js/src/index.ts
cat: /System/Volumes/Data/src/lending/backend/node_modules/uri-js/src/index.ts: No such file or directory
```
That is because `src/index.ts` is not part of the `uri-js` package at all:
```
(lending-dev) (i386)(v18.14.2) /src/lending/backend/node_modules/uri-js (master) $ ll -R
total 256
drwxr-xr-x     8 mmillerick  wheel     256 May 22 08:52 .
drwxr-xr-x  1493 mmillerick  wheel   47776 May 22 08:52 ..
-rw-r--r--@    1 mmillerick  wheel    6148 May 22 08:52 .DS_Store
-rwxr-xr-x     1 mmillerick  wheel    1452 May 22 08:36 LICENSE
-rwxr-xr-x     1 mmillerick  wheel    6416 May 22 08:36 README.md
drwxr-xr-x     5 mmillerick  wheel     160 May 22 08:52 dist
-rwxr-xr-x     1 mmillerick  wheel    2172 May 22 08:36 package.json
-rwxr-xr-x     1 mmillerick  wheel  103956 May 22 08:36 yarn.lock

./dist:
total 16
drwxr-xr-x   5 mmillerick  wheel   160 May 22 08:52 .
drwxr-xr-x   8 mmillerick  wheel   256 May 22 08:52 ..
-rw-r--r--@  1 mmillerick  wheel  6148 May 22 08:52 .DS_Store
drwxr-xr-x   8 mmillerick  wheel   256 May 22 08:36 es5
drwxr-xr-x  18 mmillerick  wheel   576 May 22 08:36 esnext

./dist/es5:
total 536
drwxr-xr-x  8 mmillerick  wheel     256 May 22 08:36 .
drwxr-xr-x  5 mmillerick  wheel     160 May 22 08:52 ..
-rwxr-xr-x  1 mmillerick  wheel    2446 May 22 08:36 uri.all.d.ts
-rwxr-xr-x  1 mmillerick  wheel   57304 May 22 08:36 uri.all.js
-rwxr-xr-x  1 mmillerick  wheel  102192 May 22 08:36 uri.all.js.map
-rwxr-xr-x  1 mmillerick  wheel    2446 May 22 08:36 uri.all.min.d.ts
-rwxr-xr-x  1 mmillerick  wheel   17200 May 22 08:36 uri.all.min.js
-rwxr-xr-x  1 mmillerick  wheel   83083 May 22 08:36 uri.all.min.js.map

./dist/esnext:
total 208
drwxr-xr-x  18 mmillerick  wheel    576 May 22 08:36 .
drwxr-xr-x   5 mmillerick  wheel    160 May 22 08:52 ..
-rwxr-xr-x   1 mmillerick  wheel     23 May 22 08:36 index.d.ts
-rwxr-xr-x   1 mmillerick  wheel    537 May 22 08:36 index.js
-rwxr-xr-x   1 mmillerick  wheel    747 May 22 08:36 index.js.map
-rwxr-xr-x   1 mmillerick  wheel     97 May 22 08:36 regexps-iri.d.ts
-rwxr-xr-x   1 mmillerick  wheel    114 May 22 08:36 regexps-iri.js
-rwxr-xr-x   1 mmillerick  wheel    192 May 22 08:36 regexps-iri.js.map
-rwxr-xr-x   1 mmillerick  wheel    160 May 22 08:36 regexps-uri.d.ts
-rwxr-xr-x   1 mmillerick  wheel   7813 May 22 08:36 regexps-uri.js
-rwxr-xr-x   1 mmillerick  wheel   8283 May 22 08:36 regexps-uri.js.map
drwxr-xr-x  23 mmillerick  wheel    736 May 22 08:36 schemes
-rwxr-xr-x   1 mmillerick  wheel   2446 May 22 08:36 uri.d.ts
-rwxr-xr-x   1 mmillerick  wheel  20153 May 22 08:36 uri.js
-rwxr-xr-x   1 mmillerick  wheel  19219 May 22 08:36 uri.js.map
-rwxr-xr-x   1 mmillerick  wheel    343 May 22 08:36 util.d.ts
-rwxr-xr-x   1 mmillerick  wheel   1114 May 22 08:36 util.js
-rwxr-xr-x   1 mmillerick  wheel   1715 May 22 08:36 util.js.map

./dist/esnext/schemes:
total 184
drwxr-xr-x  23 mmillerick  wheel   736 May 22 08:36 .
drwxr-xr-x  18 mmillerick  wheel   576 May 22 08:36 ..
-rwxr-xr-x   1 mmillerick  wheel   108 May 22 08:36 http.d.ts
-rwxr-xr-x   1 mmillerick  wheel   959 May 22 08:36 http.js
-rwxr-xr-x   1 mmillerick  wheel   841 May 22 08:36 http.js.map
-rwxr-xr-x   1 mmillerick  wheel   108 May 22 08:36 https.d.ts
-rwxr-xr-x   1 mmillerick  wheel   212 May 22 08:36 https.js
-rwxr-xr-x   1 mmillerick  wheel   312 May 22 08:36 https.js.map
-rwxr-xr-x   1 mmillerick  wheel   359 May 22 08:36 mailto.d.ts
-rwxr-xr-x   1 mmillerick  wheel  7746 May 22 08:36 mailto.js
-rwxr-xr-x   1 mmillerick  wheel  7209 May 22 08:36 mailto.js.map
-rwxr-xr-x   1 mmillerick  wheel   279 May 22 08:36 urn-uuid.d.ts
-rwxr-xr-x   1 mmillerick  wheel   868 May 22 08:36 urn-uuid.js
-rwxr-xr-x   1 mmillerick  wheel   832 May 22 08:36 urn-uuid.js.map
-rwxr-xr-x   1 mmillerick  wheel   324 May 22 08:36 urn.d.ts
-rwxr-xr-x   1 mmillerick  wheel  2050 May 22 08:36 urn.js
-rwxr-xr-x   1 mmillerick  wheel  1939 May 22 08:36 urn.js.map
-rwxr-xr-x   1 mmillerick  wheel   228 May 22 08:36 ws.d.ts
-rwxr-xr-x   1 mmillerick  wheel  1659 May 22 08:36 ws.js
-rwxr-xr-x   1 mmillerick  wheel  1610 May 22 08:36 ws.js.map
-rwxr-xr-x   1 mmillerick  wheel   108 May 22 08:36 wss.d.ts
-rwxr-xr-x   1 mmillerick  wheel   198 May 22 08:36 wss.js
-rwxr-xr-x   1 mmillerick  wheel   307 May 22 08:36 wss.js.map
```
Similar to the last crash I reported, the normal view of the extension does not open when this happen, and it instead reverts back to file selection:
![image](https://github.com/microsoft/deoptexplorer-vscode/assets/26394493/bbe150af-657c-42d5-aaea-b967aa3021b3)

Let me know if additional information is needed.  I would provide my `package.json` and package-lock.json`, but unfortunately it is so filled with proprietary internal packages, I doubt it would be of any help.

**Comment by millerick** [comment]
Seems to be the same as https://github.com/microsoft/deoptexplorer-vscode/issues/10
